#dicionario

nomebebe=input('Digite o nome do bebê: ')
print(nomebebe)
dn_bebe=str(input("Digite a Data de nascimento do bebê: "))
print(f'Nasceu em: {dn_bebe}')
peso_bebe=float(input('Digite o peso do bebê em gramas: '))
print(f'Peso de nascimento é de:  {peso_bebe} gramas')
tamanho_bebe=float(input('Digite o tamanho do bebê em cm: '))
nome_mae=input('Digite o nome da mãe: ')
endereco=input('Digite o endereço da mãe do bebê: ')
tel_mae=input('Digite o número telefônico da mãe: ')
dn_mae=input('Digite a data de nascimento da mãe: ')
medico=input('Digite o nome do médico responsável pelo parto: ')
crm=input('Digite o número CRM do médico: ')
cel_med=input('Digite o número celular do médico: ')
espec_M=input('Digite a especialidade médica: ')
